In [3]:
! pip install scikit-learn

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/


In [5]:
from sklearn.datasets import load_iris
iris = load_iris()
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
# 数据所属的真实标签
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
# 数据维度
iris.data.shape

(150, 4)

In [8]:
# 数据标签的名字
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
iris = load_iris()
print("iris 数据集的大小:",iris.data.shape)
print("目标数据集的大小:",iris.target.shape)
X_train,X_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size=0.4,random_state=0)
print("生成的训练集的特征个数（数据个数）:",X_train.shape)
print("生成的训练集的标签个数（样本个数）:",y_train.shape)
print("生成的测试集的特征个数（数据个数）:",X_test.shape)
print("生成的测试集的标签个数（样本个数）:",y_test.shape)
print("iris数据集前五行数据:",iris.data[:5])
print("生成的训练集前五行数据:",X_train[:5])
print("生成的测试集前五行数据:",X_test[:5])

iris 数据集的大小: (150, 4)
目标数据集的大小: (150,)
生成的训练集的特征个数（数据个数）: (90, 4)
生成的训练集的标签个数（样本个数）: (90,)
生成的测试集的特征个数（数据个数）: (60, 4)
生成的测试集的标签个数（样本个数）: (60,)
iris数据集前五行数据: [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
生成的训练集前五行数据: [[6.  3.4 4.5 1.6]
 [4.8 3.1 1.6 0.2]
 [5.8 2.7 5.1 1.9]
 [5.6 2.7 4.2 1.3]
 [5.6 2.9 3.6 1.3]]
生成的测试集前五行数据: [[5.8 2.8 5.1 2.4]
 [6.  2.2 4.  1. ]
 [5.5 4.2 1.4 0.2]
 [7.3 2.9 6.3 1.8]
 [5.  3.4 1.5 0.2]]


In [10]:
! pip install pip-autoremove

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/


In [11]:
! pip-autoremove scikit-learn

scikit-learn 1.7.2 (/opt/homebrew/Caskroom/miniconda/base/envs/ioe/lib/python3.10/site-packages)
    numpy 2.2.6 (/opt/homebrew/Caskroom/miniconda/base/envs/ioe/lib/python3.10/site-packages)
    scipy 1.15.3 (/opt/homebrew/Caskroom/miniconda/base/envs/ioe/lib/python3.10/site-packages)
    joblib 1.5.2 (/opt/homebrew/Caskroom/miniconda/base/envs/ioe/lib/python3.10/site-packages)
    threadpoolctl 3.6.0 (/opt/homebrew/Caskroom/miniconda/base/envs/ioe/lib/python3.10/site-packages)
Uninstall (y/N)? ^C
