In [1]:
import warnings
warnings.filterwarnings("ignore")

from sklearn import preprocessing
import numpy as np
X_train = np.array([[1.,-1.,2.],
                    [2.,0.,0.],
                    [0.,1.,-1.]])
# 数据标准化
X_scaled = preprocessing.scale(X_train)
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [2]:
X_scaled.mean(axis=0)

array([0., 0., 0.])

In [3]:
X_scaled.std(axis=0)

array([1., 1., 1.])

In [4]:
# StandardScaler计算数据集的均值和标准差
scaler = preprocessing.StandardScaler().fit(X_train)
scaler.mean_

array([1.        , 0.        , 0.33333333])

In [5]:
scaler.scale_

array([0.81649658, 0.81649658, 1.24721913])

In [6]:
scaler.transform(X_train)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [7]:
# 设置特征值的范围[0,1]
# MinMaxScaler
min_max_scaler = preprocessing.MinMaxScaler()
X_train_minmax = min_max_scaler.fit_transform(X_train)
X_train_minmax

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.5       , 0.33333333],
       [0.        , 1.        , 0.        ]])

In [8]:
# 归一化
X_train_normalized = preprocessing.normalize(X_train,norm='l2')
X_train_normalized

array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])

In [9]:
normalizer = preprocessing.Normalizer().fit(X_train)
X_train_normalizer = normalizer.transform(X_train)
X_train_normalizer

array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])

In [10]:
# 二值化(特征)
binarizer = preprocessing.Binarizer().fit(X_train)
X_train_bin = binarizer.transform(X_train)
X_train_bin

array([[1., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [11]:
# 二值化自己设置阈值
binarizer = preprocessing.Binarizer(threshold=1.5)
X_train_bin = binarizer.transform(X_train)
X_train_bin

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 0.]])

In [12]:
# 编码类别特征
# y_train = np.array([["male","female"],
#                     ["from Europe","from US","from China"],
#                     ["use xiaomi","use huawei","use iphone","use oppo"]], dtype="object")
y_train = np.array([[0,0,0],[1,1,1],[0,2,2],[1,0,3]]) # 数据矩阵角度
enc = preprocessing.OneHotEncoder(categories='auto')
enc.fit(y_train)
enc.transform([[0,1,3]]).toarray()
# 标签编码会让机器学习认为对这些进行标较，不符合原意
# le = preprocessing.LabelEncoder()
# le.fit([1,5,67,100])
# le.transform([1,1,100,67,5])

array([[1., 0., 0., 1., 0., 0., 0., 0., 1.]])

In [13]:
# 填补缺失值
from sklearn import impute
imp = impute.SimpleImputer(missing_values=np.nan, strategy="mean")
imp.fit([[1,2],[np.nan,3],[7,6]])
x = [[np.nan,2],[6,np.nan],[7,6]]
imp.transform(x)

array([[4.        , 2.        ],
       [6.        , 3.66666667],
       [7.        , 6.        ]])